export var sources = [
  { n: 1, title: "David Jones (video game developer)", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/David_Jones_(video_game_developer)" },
  { n: 2, title: "Rockstar North", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rockstar_North" },
  { n: 3, title: "Lemmings (video game)", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Lemmings_(video_game)" },
  { n: 4, title: "GTA creator Dave Jones: You never know when you've got a hit idea", pub: "GamesBeat, 2018", url: "https://gamesbeat.com/grand-theft-auto-creator-dave-jones-you-never-know-when-youve-got-a-hit-idea/" },
  { n: 5, title: "Grand Theft Auto (1997)", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto_(video_game)" },
  { n: 6, title: "The Making of Grand Theft Auto", pub: "Time Extension", url: "https://www.timeextension.com/features/the-making-of-grand-theft-auto-the-start-of-the-370-million-selling-gta-franchise" },
  { n: 7, title: "The Replay Interviews: Gary Penn", pub: "Game Developer", url: "https://www.gamedeveloper.com/design/the-replay-interviews-gary-penn" },
  { n: 8, title: "GTA dev releases original 'Race'n'Chase' design document", pub: "GameSpot, 2011", url: "https://www.gamespot.com/articles/gta-dev-releases-original-design-document/1100-6305294/" },
  { n: 9, title: "GTA would never have happened without Max Clifford", pub: "KitGuru", url: "https://www.kitguru.net/gaming/jon-martindale/gta-would-never-have-happened-without-max-clifford/" },
  { n: 10, title: "Sam Houser", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Sam_Houser" },
  { n: 11, title: "Dan Houser", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Dan_Houser" },
  { n: 12, title: "Take-Two Interactive", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Take-Two_Interactive" },
  { n: 13, title: "Take-Two 8-K: acquisition of BMG Interactive assets", pub: "SEC EDGAR, March 1998", url: "https://www.sec.gov/Archives/edgar/data/0000946581/000089155498000293/0000891554-98-000293.txt" },
  { n: 14, title: "Rockstar Games", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rockstar_Games" },
  { n: 15, title: "Take-Two Interactive buys DMA Design for $11m", pub: "Tech Monitor, Sept 1999", url: "https://www.techmonitor.ai/technology/take_two_interactive_buys_dma_design_for_11m" },
  { n: 16, title: "Grand Theft Auto III", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto_III" },
  { n: 17, title: "PS2's GTA exclusivity came because Sony was 'worried when we saw Xbox coming'", pub: "GamesRadar, 2024", url: "https://www.gamesradar.com/games/grand-theft-auto/playstation-2s-gta-exclusivity-came-because-sony-was-worried-when-we-saw-xbox-coming-and-it-wasnt-clear-that-grand-theft-auto-3-was-going-to-be-as-huge-as-it-was/" },
  { n: 18, title: "Dan Houser: no one outside the company was excited about GTA III", pub: "Notebookcheck (via GamesRadar), 2025", url: "https://www.notebookcheck.net/Dan-Houser-explains-that-no-one-was-waiting-for-the-release-of-GTA-3-except-the-developers.1169946.0.html" },
  { n: 19, title: "The Road to Ruin: Inside Rockstar Games", pub: "David Kushner, Wired, May 2007", url: "https://davidkushner.com/article/the-road-to-ruin/" },
  { n: 20, title: "Grand Theft Auto: Vice City", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto:_Vice_City" },
  { n: 21, title: "Grand Theft Auto: San Andreas", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto:_San_Andreas" },
  { n: 22, title: "Hot Coffee (minigame)", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Hot_Coffee_(minigame)" },
  { n: 23, title: "Makers of Grand Theft Auto: San Andreas settle FTC charges", pub: "Federal Trade Commission, June 8, 2006", url: "https://www.ftc.gov/news-events/news/press-releases/2006/06/makers-grand-theft-auto-san-andreas-settle-ftc-charges" },
  { n: 24, title: "Hot Coffee, stock option suit settled for $20.1 million", pub: "GameSpot, Sept 2009", url: "https://www.gamespot.com/articles/hot-coffee-stock-option-suit-settled-for-201-million/1100-6216620/" },
  { n: 25, title: "Take-Two, Thompson settle Bully and GTA IV suits", pub: "JURIST, April 2007", url: "https://www.jurist.org/news/2007/04/take-two-thompson-settle-bully-gta4/" },
  { n: 26, title: "Jack Thompson disbarred", pub: "GameSpot, Sept 2008", url: "https://www.gamespot.com/articles/jack-thompson-disbarred/1100-6198187/" },
  { n: 27, title: "Interview with Sam Houser (Develop)", pub: "The GTA Place, Aug 2008", url: "https://thegtaplace.com/news/19458/interview-with-sam-houser/" },
  { n: 28, title: "SEC charges former Take-Two CEO Ryan Brant with options backdating", pub: "SEC press release, Feb 2007", url: "https://www.sec.gov/news/press/2007/2007-20.htm" },
  { n: 29, title: "Take-Two board revolt", pub: "Forbes, March 29, 2007", url: "https://www.forbes.com/2007/03/29/take-two-board-revolt-markets-equity-cx_rr_0329markets40.html" },
  { n: 30, title: "EA's Take-Two takeover bid turns hostile", pub: "GameSpot, March 2008", url: "https://www.gamespot.com/articles/eas-take-two-takeover-bid-turns-hostile/1100-6187712/" },
  { n: 31, title: "EA gives up hostile bid for Take-Two", pub: "SFGate, Sept 2008", url: "https://www.sfgate.com/business/article/ea-gives-up-hostile-bid-for-take-two-3199748.php" },
  { n: 32, title: "Grand Theft Auto IV", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto_IV" },
  { n: 33, title: "GTA IV sets sales records: 6 million units, $500 million first week", pub: "Engadget, May 2008", url: "https://www.engadget.com/2008-05-07-gta-iv-sets-sales-records-with-6-million-unit-500-million-fir.html" },
  { n: 34, title: "EA pays $48 million for Criterion", pub: "GameSpot, July 2004", url: "https://www.gamespot.com/articles/ea-pays-48-million-for-criterion/1100-6104101/" },
  { n: 35, title: "Grand Theft Auto IV has sold 25 million units to date", pub: "Game Informer, July 2013", url: "https://gameinformer.com/b/news/archive/2013/07/30/grand-theft-auto-iv-has-sold-25-million-units-to-date.aspx" },
  { n: 36, title: "Rockstar: more than 1,000 people made GTA V", pub: "GameSpot, 2013", url: "https://www.gamespot.com/articles/rockstar-more-than-1000-people-made-gtav/1100-6415330/" },
  { n: 37, title: "New GTA V release tipped to rake in £1bn in sales", pub: "The Scotsman, Sept 2013", url: "https://www.scotsman.com/whats-on/arts-and-entertainment/new-gta-v-release-tipped-to-rake-in-ps1bn-in-sales-2463312" },
  { n: 38, title: "Take-Two 8-K: GTA V first-day retail sales exceed $800 million", pub: "SEC EDGAR, Sept 18, 2013", url: "https://www.sec.gov/Archives/edgar/data/946581/000110465913070819/a13-20938_1ex99d1.htm" },
  { n: 39, title: "Take-Two 8-K: GTA V passes $1 billion in three days", pub: "SEC EDGAR, Sept 20, 2013", url: "https://www.sec.gov/Archives/edgar/data/946581/000110465913071387/a13-21085_1ex99d1.htm" },
  { n: 40, title: "Confirmed: Grand Theft Auto breaks six sales world records", pub: "Guinness World Records, Oct 2013", url: "https://www.guinnessworldrecords.com/news/2013/10/confirmed-grand-theft-auto-breaks-six-sales-world-records-51900" },
  { n: 41, title: "GTA V has made more money than any other entertainment product ever", pub: "Push Square (MarketWatch / Cowen), April 2018", url: "https://www.pushsquare.com/news/2018/04/grand_theft_auto_v_has_made_more_money_than_any_other_entertainment_product_ever" },
  { n: 42, title: "GTA V has become the most profitable piece of entertainment of all time", pub: "KitGuru, April 2018", url: "https://www.kitguru.net/gaming/damien-cox/gta-v-has-become-the-most-profitable-piece-of-entertainment-of-all-time/" },
  { n: 43, title: "GTA V in 8 years: $6.4 billion earned from 150 million sales", pub: "TweakTown, 2021", url: "https://www.tweaktown.com/news/81664/gta-in-8-years-6-4-billion-earned-from-150-million-sales/index.html" },
  { n: 44, title: "GTA V surpasses 230 million sales months before GTA VI touches down", pub: "Game Developer, Aug 7, 2026", url: "https://www.gamedeveloper.com/business/gta-v-surpasses-230-million-sales-months-before-gta-vi-touches-down" },
  { n: 45, title: "Free GTA V crashes the Epic Games Store", pub: "Variety, May 2020", url: "https://variety.com/2020/digital/news/epic-games-store-crashes-gta-v-free-1234607129/" },
  { n: 46, title: "Lohan v. Take-Two Interactive Software, Inc.", pub: "New York Court of Appeals, March 2018 (Justia)", url: "https://law.justia.com/cases/new-york/court-of-appeals/2018/24.html" },
  { n: 47, title: "Rockstar's GTA Online apology is a $500,000 direct deposit", pub: "Forbes, Oct 2013", url: "https://www.forbes.com/sites/insertcoin/2013/10/11/rockstars-gta-online-apology-is-a-500000-direct-deposit/" },
  { n: 48, title: "Zelnick: 70% of connected GTA V players play GTA Online", pub: "Engadget, April 2014", url: "https://www.engadget.com/2014-04-10-2ks-zelnick-70-of-connected-gta5-players-play-gta-online.html" },
  { n: 49, title: "Take-Two reports results for fiscal year 2017", pub: "Take-Two Investor Relations, May 2017", url: "https://ir.take2games.com/static-files/8ff61573-b743-457e-91ce-6bd16a79033e" },
  { n: 50, title: "Take-Two 2018 Annual Report", pub: "Take-Two Investor Relations", url: "https://ir.take2games.com/static-files/5ff20a63-302f-4778-9053-17d5ea35b9f8" },
  { n: 51, title: "Take-Two reports results for fiscal year 2021", pub: "Business Wire, May 2021", url: "https://www.businesswire.com/news/home/20210518005935/en" },
  { n: 52, title: "Take-Two reports results for fiscal year 2023", pub: "Take-Two Investor Relations, May 2023", url: "https://www.take2games.com/ir/news/take-two-interactive-software-inc-reports-results-fiscal-year" },
  { n: 53, title: "Take-Two reports results for fiscal year 2025", pub: "Take-Two Investor Relations, May 2025", url: "https://www.take2games.com/ir/news/take-two-interactive-software-inc-reports-results-fourth-1" },
  { n: 54, title: "Take-Two reports results for fiscal year 2026", pub: "Take-Two Investor Relations, May 21, 2026", url: "https://www.take2games.com/ir/news/take-two-interactive-software-inc-reports-results-fourth-2" },
  { n: 55, title: "Take-Two 8-K: first quarter fiscal 2027 results", pub: "SEC EDGAR, Aug 7, 2026", url: "https://www.sec.gov/Archives/edgar/data/0000946581/000162828026054580/ttwo1q27earningsrelease.htm" },
  { n: 56, title: "Take-Two Interactive revenue history", pub: "StockAnalysis", url: "https://stockanalysis.com/stocks/ttwo/revenue/" },
  { n: 57, title: "GTA Online earned $1.09 billion, says SuperData", pub: "TweakTown, July 2017", url: "https://www.tweaktown.com/news/58516/gta-online-earned-1-09-billion-analyst-firm/index.html" },
  { n: 58, title: "Hackers reveal Rockstar earns over $1 million a day from GTA Online", pub: "Kotaku, April 2026", url: "https://kotaku.com/hackers-reveal-rockstar-earns-over-1-million-a-day-from-gta-online-2000687207" },
  { n: 59, title: "The Decade GTA Online Owned", pub: "The Ringer, Sept 2023", url: "https://www.theringer.com/2023/09/29/video-games/grand-theft-auto-online-gta-v-rockstar-live-service-games" },
  { n: 60, title: "GTA Online completely changed how we play, and not always for the better", pub: "Inverse, Aug 2023", url: "https://www.inverse.com/gaming/gta-online-reveal-10th-anniversary" },
  { n: 61, title: "Rockstar acquires community roleplay team Cfx.re", pub: "Game Developer, Aug 2023", url: "https://www.gamedeveloper.com/business/rockstar-acquires-community-roleplay-team-cfx-re" },
  { n: 62, title: "GTA V RP server takes the game to the top of Twitch", pub: "Streams Charts, Feb 2021", url: "https://streamscharts.com/news/gta-v-rp-server-takes-game-top-twitch-february" },
  { n: 63, title: "GTA V was the most-watched game on Twitch in 2024", pub: "Yahoo Tech, 2025", url: "https://tech.yahoo.com/gaming/articles/gta-v-most-watched-game-153015719.html" },
  { n: 64, title: "If you invested $1,000 in Take-Two when GTA V was released", pub: "Benzinga via Investing.com", url: "https://uk.investing.com/news/stock-market-news/if-you-invested-1000-in-taketwo-stock-when-grand-theft-auto-v-was-released-heres-how-much-youd-have-now-3259774" },
  { n: 65, title: "Take-Two Interactive market cap history", pub: "StockAnalysis, Aug 28, 2026", url: "https://stockanalysis.com/stocks/ttwo/market-cap/" },
  { n: 66, title: "Red Dead Redemption 2 earns record $725 million opening weekend", pub: "Variety, Oct 2018", url: "https://variety.com/2018/gaming/news/red-dead-redemption-2-opening-weekend-1203014421/" },
  { n: 67, title: "Take-Two to buy FarmVille creator Zynga for $12.7 billion", pub: "CNBC, Jan 2022", url: "https://www.cnbc.com/2022/01/10/take-two-interactive-to-buy-farmville-creator-zynga-for-12point7-billion.html" },
  { n: 68, title: "'We were working 100-hour weeks': Dan Houser on Red Dead Redemption 2", pub: "Kotaku, Oct 2018", url: "https://kotaku.com/we-were-working-100-hour-weeks-red-dead-redemption-2-h-1829758281" },
  { n: 69, title: "Rockstar co-founder Dan Houser is leaving the studio", pub: "Game Developer, Feb 2020", url: "https://www.gamedeveloper.com/production/rockstar-games-co-founder-dan-houser-is-leaving-the-studio" },
  { n: 70, title: "Former Rockstar boss Leslie Benzies sues Rockstar for $150 million", pub: "PC Gamer, April 2016", url: "https://www.pcgamer.com/former-rockstar-boss-leslie-benzies-sues-rockstar-for-150-million/" },
  { n: 71, title: "MindsEye", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/MindsEye" },
  { n: 72, title: "Grand Theft Auto: The Trilogy – The Definitive Edition", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto:_The_Trilogy_%E2%80%93_The_Definitive_Edition" },
  { n: 73, title: "GTA boss explains the 13-year wait for GTA 6", pub: "NME, May 29, 2026", url: "https://www.nme.com/news/gaming-news/grand-theft-auto-boss-explains-wait-for-6-online-rockstar-3948153" },
  { n: 74, title: "Report: GTA 6 in the works since 2014; Rockstar reforms crunch culture (Bloomberg)", pub: "Game Informer, July 2022", url: "https://gameinformer.com/report/2022/07/27/report-grand-theft-auto-6-co-stars-a-female-protagonist-rockstar-adopts-more" },
  { n: 75, title: "Rockstar confirms GTA VI leak after network intrusion", pub: "Variety, Sept 2022", url: "https://variety.com/2022/digital/news/grand-theft-auto-6-leak-rockstar-games-hack-1235376727" },
  { n: 76, title: "GTA 6 hacker sentenced to an indefinite hospital order", pub: "TechRadar, Dec 2023", url: "https://www.techradar.com/gaming/gta-6-hacker-who-intended-to-return-to-cyber-crime-as-soon-as-possible-sentenced-to-an-indefinite-hospital-order" },
  { n: 77, title: "GTA VI first look becomes most viewed videogame trailer in 24 hours", pub: "Guinness World Records, Dec 2023", url: "https://www.guinnessworldrecords.com/news/2023/12/grand-theft-auto-vi-first-look-becomes-most-viewed-videogame-trailer-in-24-hours-762030" },
  { n: 78, title: "Tom Petty's 'Love Is a Long Road' streams spike after GTA 6 trailer", pub: "Kotaku, Dec 2023", url: "https://kotaku.com/gta-6-vi-trailer-song-tom-petty-love-is-a-long-road-1851077993" },
  { n: 79, title: "GTA 6 delayed to May 2026; Rockstar apologizes", pub: "Variety, May 2, 2025", url: "https://variety.com/2025/gaming/news/gta-6-release-date-may-2026-rockstar-games-apologizes-1236384841/" },
  { n: 80, title: "GTA 6 delayed to November 19, 2026", pub: "Variety, Nov 6, 2025", url: "https://variety.com/2025/gaming/news/gta-6-release-delayed-november-2026-1236571679/" },
  { n: 81, title: "Take-Two shares sink after GTA VI delay", pub: "CNBC, Nov 6, 2025", url: "https://www.cnbc.com/2025/11/06/take-two-gta-vi-delay.html" },
  { n: 82, title: "GTA 6 trailer 2 racks up 475 million views in 24 hours", pub: "TechRadar, May 2025", url: "https://www.techradar.com/gaming/the-latest-grand-theft-auto-6-trailer-has-set-a-major-record-by-racking-up-475-million-views-in-just-24-hours" },
  { n: 83, title: "Union disputes Rockstar's leak claim after firings", pub: "The Register, Nov 6, 2025", url: "https://www.theregister.com/2025/11/06/union_brands_rockstars_leak_claim/" },
  { n: 84, title: "Rockstar Games faces full hearing over alleged union-busting", pub: "The Register, June 19, 2026", url: "https://www.theregister.com/offbeat/2026/06/19/rockstar-games-faces-full-hearing-over-alleged-union-busting/5258514" },
  { n: 85, title: "Rockstar confirms no disc version of GTA 6 at launch; pre-orders and pricing", pub: "VGC, June 24, 2026", url: "https://www.videogameschronicle.com/news/rockstar-confirms-there-will-be-no-disc-version-of-gta6-at-launch/" },
  { n: 86, title: "Zelnick: GTA 6's $80 price is 'an incredible bargain'", pub: "TechSpot (CNBC interview), Aug 11, 2026", url: "https://www.techspot.com/news/113435-gta-6-80-price-bargain-because-rockstar-delivers.html" },
  { n: 87, title: "Analyst expects $100 price, $1.5B+ cost, $10B lifetime for GTA 6", pub: "GamesRadar (Wedbush), 2025", url: "https://www.gamesradar.com/games/grand-theft-auto/analyst-says-i-expect-a-usd100-price-point-for-gta-6-estimates-rockstars-development-cost-is-over-usd1-5-billion-and-predicts-it-will-earn-usd10-billion-lifetime-and-another-usd500-million-annually-from-gta-online/" },
  { n: 88, title: "GTA 6 predicted to be one of the biggest entertainment launches in history (DFC)", pub: "TechRadar", url: "https://www.techradar.com/gaming/gaming-industry/gta-6-is-predicted-to-be-one-of-the-biggest-entertainment-launches-in-history" },
  { n: 89, title: "Newzoo: GTA 6 has the strongest pre-order campaign on record", pub: "VGC, July 16, 2026", url: "https://www.videogameschronicle.com/news/analytics-firm-says-gta-6-has-the-strongest-pre-order-campaign-on-record-is-on-track-to-sell-37-51-million-in-its-first-week/" },
  { n: 90, title: "Take-Two stock falls as FY27 guidance offsets GTA VI hype", pub: "Invezz via TradingView, May 2026", url: "https://www.tradingview.com/news/invezz:ebedf53d6094b:0-take-two-stock-falls-as-weak-fy27-guidance-offsets-gta-vi-hype/" },
  { n: 91, title: "Take-Two CEO Strauss Zelnick isn't doing a victory lap before GTA VI sales start", pub: "GamesBeat, Aug 7, 2026", url: "https://gamesbeat.com/take-two-ceo-strauss-zelnick-isnt-doing-a-victory-lap-before-gta-vi-sales-start-exclusive-interview/" },
  { n: 92, title: "Video game industry outlook 2026: Mat Piscatella on GTA 6", pub: "Lords of Gaming, Feb 2026", url: "https://lordsofgaming.net/2026/02/video-game-industry-outlook-2026-mat-piscatella-on-hardware-subscriptions-and-gta-6/" },
  { n: 93, title: "GTA 6 delay could wipe $2.7 billion from the games industry (Ampere)", pub: "GameSpot, May 2025", url: "https://www.gamespot.com/articles/gta-6-delay-could-wipe-out-a-jaw-dropping-amount-of-money-from-global-games-industry/1100-6531664/" },
  { n: 94, title: "Squadron 42 delayed to avoid 'the buzzsaw of GTA6'", pub: "Kotaku, Aug 28, 2026", url: "https://kotaku.com/star-citizen-squadron-42-delay-gta-6-chris-roberts-rockstar-billion-dollars-2000729284" },
  { n: 95, title: "GTA 6 'Extended Look' to premiere on Netflix", pub: "Variety, Aug 2026", url: "https://variety.com/2026/tv/news/gta-6-netflix-trailer-extended-look-release-1236845475/" },
  { n: 96, title: "GTA 6 hits No. 1 on Netflix and catapults streamer's web viewership 125%", pub: "Forbes, Aug 28, 2026", url: "https://www.forbes.com/sites/paultassi/2026/08/28/gta-6-hits-no-1-on-netflix-and-catapults-streamers-web-viewership-125/" },
  { n: 97, title: "Rockstar's official statement on the GTA 6 leaks", pub: "Kotaku, Aug 26, 2026", url: "https://kotaku.com/rockstar-gta-6-leaks-grand-theft-auto-cyberleek-official-statement-2000728341" },
  { n: 98, title: "Rockstar reveals a swathe of new GTA 6 details (Dazed interview)", pub: "VGC, Aug 27, 2026", url: "https://www.videogameschronicle.com/news/rockstar-reveals-a-swathe-of-new-gta-6-details-ahead-of-the-netflix-extended-look/" },
  { n: 99, title: "Tech analyst: 'They should be charging like $200 for this'", pub: "Kotaku, July 2026", url: "https://kotaku.com/tech-analyst-calls-gta-6s-80-price-tag-ridiculous-they-should-be-charging-like-200-for-this-2000715214" },
  { n: 100, title: "The CEO behind GTA VI doesn't play video games", pub: "Fortune, May 2026", url: "https://fortune.com/2026/05/06/ceo-take-two-interactive-software-strauss-zelnick-doesnt-play-video-games-grand-theft-auto-vi/" },
  { n: 101, title: "Controversy erupts over Rockstar San Diego employee allegations ('Rockstar Spouse')", pub: "Game Developer, Jan 2010", url: "https://www.gamedeveloper.com/game-platforms/controversy-erupts-over-rockstar-san-diego-employee-allegations" },
  { n: 102, title: "Rockstar San Diego", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rockstar_San_Diego" },
  { n: 103, title: "GTA 6 hacker Arion Kurtaj moved to prison ahead of November 2026 retrial", pub: "gHacks (via BBC), July 17, 2026", url: "https://www.ghacks.net/2026/07/17/gta-6-hacker-arion-kurtaj-moved-from-secure-hospital-to-prison-ahead-of-november-2026-retrial/" },
  { n: 104, title: "Rockstar is already calling GTA 6 'the largest game launch in history'", pub: "PC Gamer, Oct 2025", url: "https://www.pcgamer.com/games/grand-theft-auto/rockstar-is-already-calling-gta-6-the-largest-game-launch-in-history-7-months-out-from-release-counting-a-few-hundred-million-chickens-before-theyve-hatched/" },
  { n: 105, title: "GTA V slams into controversy with torture scene", pub: "TIME, Sept 2013", url: "https://entertainment.time.com/2013/09/19/grand-theft-auto-v-slams-into-controversy-with-gratuitous-torture-scene/" },
  { n: 106, title: "Rockstar Games confirms GTA VI 'well underway'", pub: "Gematsu, Feb 4, 2022", url: "https://www.gematsu.com/2022/02/rockstar-games-active-development-for-the-next-entry-in-the-grand-theft-auto-series-is-well-underway" },
];
sources.push(
  { n: 107, title: "Grand Theft Auto V", pub: "Wikipedia", url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto_V" },
  { n: 108, title: "GTA V's map is bigger than GTA IV, San Andreas and Red Dead Redemption combined", pub: "VideoGamer, 2013", url: "https://www.videogamer.com/news/gta-5s-map-is-bigger-than-gta-4-san-andreas-and-red-dead-redemption-combined/" }
);
