export var sources = [
  {
    n: 1,
    title: "OpenAI – Hugging Face Incident Technical Report",
    pub: "OpenAI · August 26, 2026 · PDF",
    url: "https://cdn.openai.com/pdf/67869394-cb91-4c12-888c-5cbd85c7814c/OpenAI-Hugging-Face%20Incident-Technical-Report.pdf",
    note: "The fullest first-party account: the evaluation environment, the May training behaviour, the Artifactory compromise, the Hugging Face intrusion, the July 19 compromise of OpenAI's own research cluster, the alignment findings, the remediation plan, and a timestamped table of key technical events. Nearly every timestamp on this page comes from that table.",
  },
  {
    n: 2,
    title: "The Hugging Face incident and the road ahead",
    pub: "OpenAI · August 26, 2026",
    url: "https://openai.com/index/hugging-face-incident-and-the-road-ahead/",
    note: "The narrative companion published alongside the technical report. Cited here for framing and for the July 13–19 characterisation of the second wave.",
  },
  {
    n: 3,
    title: "Hugging Face model evaluation security incident",
    pub: "OpenAI · July 21, 2026",
    url: "https://openai.com/index/hugging-face-model-evaluation-security-incident/",
    note: "The original disclosure, published the day after OpenAI connected its own internal alert to the Hugging Face break-in. Much thinner than what followed.",
  },
  {
    n: 4,
    title: "Brief independent investigation of agents' behavior, reasoning and collaboration in the OpenAI / Hugging Face hacking incident",
    pub: "METR & Redwood Research · August 26, 2026",
    url: "https://metr.org/blog/2026-08-26-openai-hugging-face-incident-investigation/",
    note: "Ryan Greenblatt, Ajeya Cotra and Hjalmar Wijk, working on OpenAI's premises across three visits totalling six days, unpaid. Source for agent counts, message volumes, coordination norms, the self-risking experiments, the chain-of-thought quotations and the transcript spoofing. Scope: June 26 to July 13, with analysis concentrated on July 7 onward.",
  },
  {
    n: 5,
    title: "Anatomy of a Frontier Lab Agent Intrusion: A Technical Timeline of the July 2026 Incident",
    pub: "Hugging Face · July 27, 2026",
    url: "https://huggingface.co/blog/agent-intrusion-technical-timeline",
    note: "The defender's forensic reconstruction of roughly 17,600 recovered actions between July 9 and July 13: both injection vectors, the lateral movement, the improvised command-and-control protocol, and what was and was not reached.",
  },
  {
    n: 6,
    title: "Security incident disclosure — July 2026",
    pub: "Hugging Face · July 16, 2026",
    url: "https://huggingface.co/blog/security-incident-july-2026",
    note: "Hugging Face's original public disclosure, written before it knew whose agents these were. Source for the guardrail-lockout account and the open-weights forensics.",
  },
  {
    n: 7,
    title: "The Hugging Face attack surprised me",
    pub: "Ajeya Cotra, Planned Obsolescence · August 28, 2026",
    url: "https://www.planned-obsolescence.org/p/the-hugging-face-attack-surprised",
    note: "One of the three independent investigators on the five things she had wrong going in. The best short read on why the findings landed harder than the early reporting suggested.",
  },
  {
    n: 8,
    title: "Brief notes on the OpenAI / Hugging Face incident",
    pub: "Alexander Barry · July 26, 2026",
    url: "https://abstatisticalconsulting.substack.com/p/brief-notes-on-the-openaihugging",
    note: "An analyst who had studied ExploitGym closely, with the benchmark authors' own estimate that only 60–70% of its tasks are solvable, and the exact wording of the prompt's targeting requirement.",
  },
  {
    n: 9,
    title: "The Rise and Fall of Agent Civilizations",
    pub: "Dwarkesh Patel · August 29, 2026",
    url: "https://www.dwarkesh.com/p/openai-huggingface",
    note: "A plain-English synthesis of both reports that framed the episode as three successive waves. Useful as a map; the three-civilisation structure is an interpretive device, not a term used in the primary sources.",
  },
  {
    n: 10,
    title: "Hugging Face Incident Initial Post-Mortem",
    pub: "Cloud Security Alliance · July 27, 2026",
    url: "https://cloudsecurityalliance.org/artifacts/hugging-face-ciso-post-mortem",
    note: "The practitioner framing, reviewed by a large CISO community and written for security leaders already running agents in production.",
  },
  {
    n: 11,
    title: "zai-org/GLM-5.2",
    pub: "Hugging Face model card",
    url: "https://huggingface.co/zai-org/GLM-5.2",
    note: "The open-weight model Hugging Face ran on its own infrastructure to decode the attacker's payloads after the commercial APIs refused the work.",
  },
  {
    n: 12,
    title: "Ryan Greenblatt on the case for AI takeover",
    pub: "Dwarkesh Podcast",
    url: "https://www.dwarkesh.com/p/ryan-greenblatt",
    note: "Recorded while Greenblatt was mid-investigation and unable to say so. Context for how the findings landed among people who had been arguing about exactly this scenario.",
  },
];
